import React, { useState } from 'react';
import PageHeader from '../../components/layout/PageHeader';
import Card from '../../components/common/Card';
import Button from '../../components/common/Button';
import Input from '../../components/common/Input';
import Select from '../../components/common/Select';
import FormGroup from '../../components/common/FormGroup';
import Toggle from '../../components/common/Toggle';
import Icon from '../../components/common/Icon';
import { OwnerFeedback, OwnerFieldGrid } from './components/OwnerPageTools';

export default function OwnerSettings() {
	const [section, setSection] = useState('profile'); const [feedback, setFeedback] = useState(null); const [alerts, setAlerts] = useState(true); const [email, setEmail] = useState(true);
	const save = (event) => { event.preventDefault(); setFeedback('Settings saved in this frontend preview.'); };
	const sections = [{ id: 'profile', label: 'Profile', icon: 'user' }, { id: 'property', label: 'Property Preferences', icon: 'building' }, { id: 'billing', label: 'Billing Settings', icon: 'credit-card' }, { id: 'notifications', label: 'Notifications', icon: 'bell' }, { id: 'security', label: 'Security', icon: 'lock' }];
	return <div className="owner-page"><PageHeader title="Settings" description="Manage your owner profile and portal preferences." /><div className="settings-grid"><nav className="settings-nav">{sections.map((item) => <button type="button" key={item.id} className={`settings-nav-item ${section === item.id ? 'active' : ''}`} onClick={() => setSection(item.id)}><Icon name={item.icon} size={16} />{item.label}</button>)}</nav><form onSubmit={save} className="settings-content"><Card title={sections.find((item) => item.id === section)?.label}>{section === 'profile' && <><OwnerFieldGrid><FormGroup label="Full Name"><Input defaultValue="Rahman Ahmed" /></FormGroup><FormGroup label="Email"><Input type="email" defaultValue="rahman.ahmed@example.com" /></FormGroup></OwnerFieldGrid><OwnerFieldGrid><FormGroup label="Phone"><Input defaultValue="+880 1712-345678" /></FormGroup><FormGroup label="Role"><Input defaultValue="Property Owner" disabled /></FormGroup></OwnerFieldGrid></>}{section === 'property' && <><FormGroup label="Default Property"><Select options={[{ value: 'abc', label: 'ABC Residence' }, { value: 'green', label: 'Green View Apartments' }]} /></FormGroup><OwnerFieldGrid><FormGroup label="Currency"><Select options={[{ value: 'bdt', label: 'BDT · ৳' }, { value: 'usd', label: 'USD · $' }]} /></FormGroup><FormGroup label="Default Billing Day"><Input type="number" defaultValue="10" /></FormGroup></OwnerFieldGrid></>}{section === 'billing' && <><FormGroup label="Default Due Date"><Input type="number" defaultValue="10" /></FormGroup><FormGroup label="Late Payment Grace Period"><Input type="number" defaultValue="5" /></FormGroup><p className="form-hint">These preferences are display-only until billing is connected to a backend.</p></>}{section === 'notifications' && <div className="settings-toggle-list"><div><div><strong>Maintenance alerts</strong><p>Notify me when a new request is submitted.</p></div><Toggle checked={alerts} onChange={(event) => setAlerts(event.target.checked)} /></div><div><div><strong>Email summaries</strong><p>Receive a weekly portfolio summary.</p></div><Toggle checked={email} onChange={(event) => setEmail(event.target.checked)} /></div></div>}{section === 'security' && <><FormGroup label="Current Password"><Input type="password" placeholder="Enter current password" /></FormGroup><OwnerFieldGrid><FormGroup label="New Password"><Input type="password" placeholder="At least 8 characters" /></FormGroup><FormGroup label="Confirm Password"><Input type="password" placeholder="Repeat new password" /></FormGroup></OwnerFieldGrid></>}<div className="settings-actions"><Button type="submit" variant="primary" icon={<Icon name="save" size={16} />}>Save Changes</Button></div></Card></form></div><OwnerFeedback message={feedback} onClose={() => setFeedback(null)} /></div>;
}
