import React, { useState } from 'react';
import PageHeader from '../../components/layout/PageHeader';
import Card from '../../components/common/Card';
import StatCard from '../../components/common/StatCard';
import Button from '../../components/common/Button';
import Icon from '../../components/common/Icon';
import Select from '../../components/common/Select';
import { reportsData } from '../../data/ownerPortalData';
import { OwnerFeedback } from './components/OwnerPageTools';

export default function OwnerReports() {
	const [feedback, setFeedback] = useState(null); const { financial, occupancy, performance } = reportsData;
	const incomeBars = [{ label: 'May', income: 72, expense: 38 }, { label: 'Jun', income: 79, expense: 44 }, { label: 'Jul', income: 84, expense: 48 }, { label: 'Aug', income: 88, expense: 46 }, { label: 'Sep', income: 94, expense: 51 }];
	return <div className="owner-page"><PageHeader title="Reports & Analytics" description="Understand income, occupancy, and collection performance across your portfolio." actions={<><Button variant="secondary" icon={<Icon name="download" size={16} />} onClick={() => setFeedback('Report export prepared for download.')}>Export</Button><Button variant="primary" icon={<Icon name="file-text" size={16} />} onClick={() => setFeedback('Report generated for September 2025.')}>Generate Report</Button></>} /><div className="report-filters"><Select options={[{ value: 'sep', label: 'September 2025' }, { value: 'aug', label: 'August 2025' }]} /><Select options={[{ value: 'all', label: 'All Properties' }, { value: 'abc', label: 'ABC Residence' }]} /><Select options={[{ value: 'portfolio', label: 'Portfolio Summary' }, { value: 'financial', label: 'Financial Report' }]} /></div><div className="owner-summary-grid"><StatCard title="Income" value={financial.totalRevenue} iconName="trending-up" iconColor="green" /><StatCard title="Expenses" value={financial.totalExpenses} iconName="credit-card" iconColor="orange" /><StatCard title="Net Income" value={financial.netOperatingIncome} iconName="dollar-sign" iconColor="blue" /><StatCard title="Margin" value={financial.margin} iconName="pie-chart" iconColor="purple" /></div><div className="reports-grid"><Card title="Income vs Expenses"><div className="report-chart"><div className="report-chart__legend"><span><i className="report-dot report-dot--income" />Income</span><span><i className="report-dot report-dot--expense" />Expenses</span></div><div className="bar-chart">{incomeBars.map((bar) => <div className="bar-chart__group" key={bar.label}><div className="bar-chart__bars"><span className="bar bar--income" style={{ height: `${bar.income}%` }} /><span className="bar bar--expense" style={{ height: `${bar.expense}%` }} /></div><small>{bar.label}</small></div>)}</div></div></Card><Card title="Occupancy"><div className="report-metric-list"><div><span>Occupied Units</span><strong>{occupancy.occupiedUnits} / {occupancy.totalUnits}</strong></div><div className="metric-progress"><span style={{ width: `${occupancy.occupancyPct}%` }} /></div><div><span>Vacant Units</span><strong>{occupancy.vacantUnits}</strong></div><div><span>Maintenance</span><strong>2</strong></div></div></Card><Card title="Payment Performance"><div className="report-metric-list"><div><span>Paid Invoices</span><strong className="text-success">{performance.paidInvoices}</strong></div><div><span>Pending Invoices</span><strong>{performance.pendingInvoices}</strong></div><div><span>Overdue Invoices</span><strong className="text-danger">{performance.overdueInvoices}</strong></div><div><span>Collection Efficiency</span><strong>{performance.collectionEfficiency}</strong></div></div></Card></div><OwnerFeedback message={feedback} onClose={() => setFeedback(null)} /></div>;
}
