import React, { useState } from 'react';
import PageHeader from '../../components/layout/PageHeader';
import Card from '../../components/common/Card';
import Button from '../../components/common/Button';
import Input from '../../components/common/Input';
import Select from '../../components/common/Select';
import FormGroup from '../../components/common/FormGroup';
import Toggle from '../../components/common/Toggle';
import Icon from '../../components/common/Icon';
import { TenantFeedback, TenantFieldGrid } from './components/TenantPageTools';

export default function TenantProfile() {
	const [section, setSection] = useState('personal'); const [feedback, setFeedback] = useState(null); const [settings, setSettings] = useState({ bills: true, payments: true, maintenance: true, notices: true, messages: true });
	const save = (event) => { event.preventDefault(); setFeedback('Profile settings saved in this frontend preview.'); };
	const sections = [{ id: 'personal', label: 'Personal Information', icon: 'user' }, { id: 'account', label: 'Account Settings', icon: 'settings' }, { id: 'notifications', label: 'Notifications', icon: 'bell' }, { id: 'security', label: 'Security', icon: 'lock' }];
	return <div className="tenant-page"><PageHeader title="Profile" description="Manage your personal information, preferences, and security." /><div className="settings-grid tenant-profile-grid"><nav className="settings-nav">{sections.map((item) => <button type="button" key={item.id} className={`settings-nav-item ${section === item.id ? 'active' : ''}`} onClick={() => setSection(item.id)}><Icon name={item.icon} size={16} />{item.label}</button>)}</nav><form onSubmit={save} className="settings-content"><Card title={sections.find((item) => item.id === section)?.label}>{section === 'personal' && <><TenantFieldGrid><FormGroup label="Full Name"><Input defaultValue="Tanjim Ahmed" /></FormGroup><FormGroup label="Email"><Input type="email" defaultValue="tanjim.ahmed@example.com" /></FormGroup></TenantFieldGrid><TenantFieldGrid><FormGroup label="Phone"><Input defaultValue="+880 1744-456789" /></FormGroup><FormGroup label="Emergency Contact"><Input defaultValue="Nusrat Ahmed · +880 1811-223344" /></FormGroup></TenantFieldGrid></>}{section === 'account' && <TenantFieldGrid><FormGroup label="Language"><Select options={[{ value: 'en', label: 'English' }, { value: 'bn', label: 'বাংলা' }]} /></FormGroup><FormGroup label="Time Zone"><Select options={[{ value: 'dhaka', label: 'Asia/Dhaka (GMT+6)' }]} /></FormGroup></TenantFieldGrid>}{section === 'notifications' && <div className="settings-toggle-list">{[['bills', 'Bill reminders', 'Receive reminders before your monthly bill is due.'], ['payments', 'Payment confirmation', 'Get a confirmation after a payment is recorded.'], ['maintenance', 'Maintenance updates', 'See changes to your maintenance requests.'], ['notices', 'Notice alerts', 'Be notified when your property posts an announcement.'], ['messages', 'Messages', 'Get alerts for new messages from your owner.']].map(([key, label, description]) => <div key={key}><div><strong>{label}</strong><p>{description}</p></div><Toggle checked={settings[key]} onChange={(event) => setSettings({ ...settings, [key]: event.target.checked })} /></div>)}</div>}{section === 'security' && <><FormGroup label="Current Password"><Input type="password" placeholder="Enter current password" /></FormGroup><TenantFieldGrid><FormGroup label="New Password"><Input type="password" placeholder="At least 8 characters" /></FormGroup><FormGroup label="Confirm Password"><Input type="password" placeholder="Repeat new password" /></FormGroup></TenantFieldGrid></>}<div className="settings-actions"><Button type="submit" variant="primary" icon={<Icon name="save" size={16} />}>Save Changes</Button></div></Card></form></div><TenantFeedback message={feedback} onClose={() => setFeedback(null)} /></div>;
}
