import React, { useState } from 'react';
import PageHeader from '../../../components/layout/PageHeader';
import Card from '../../../components/common/Card';
import StatCard from '../../../components/common/StatCard';
import Button from '../../../components/common/Button';
import Icon from '../../../components/common/Icon';
import Input from '../../../components/common/Input';
import Select from '../../../components/common/Select';
import FormGroup from '../../../components/common/FormGroup';
import Modal from '../../../components/common/Modal';
import StatusBadge from '../../../components/common/StatusBadge';
import Table from '../../../components/tables/Table';
import { AdminFeedback, AdminFieldGrid, AdminModalActions } from './AdminPageTools';

const configs = {
  users: { title: 'Users', description: 'Manage platform users and account status.', dataKey: 'users', summary: [['Total Users', '1,248', 'users', 'blue'], ['Active', '1,180', 'check-circle', 'green'], ['Pending', '42', 'clock', 'orange'], ['Suspended', '26', 'slash', 'red']], search: 'Search users...', filters: ['role', 'status'] },
  owners: { title: 'Owners', description: 'Review property owners, portfolio coverage, and account status.', dataKey: 'owners', summary: [['Total Owners', '86', 'user', 'blue'], ['Active Owners', '78', 'check-circle', 'green'], ['Pending Approval', '5', 'clock', 'orange'], ['Suspended', '3', 'slash', 'red']], search: 'Search owners...', filters: ['status'] },
  tenants: { title: 'Tenants', description: 'Manage tenant accounts across the BuildSync platform.', dataKey: 'tenants', summary: [['Total Tenants', '1,102', 'home', 'blue'], ['Active', '1,050', 'check-circle', 'green'], ['Pending', '32', 'clock', 'orange'], ['Inactive', '20', 'user-x', 'red']], search: 'Search tenants...', filters: ['property', 'owner', 'status'] },
  properties: { title: 'Properties', description: 'Manage the platform-wide property directory and approvals.', dataKey: 'properties', summary: [['Total Properties', '24', 'building', 'blue'], ['Active', '22', 'check-circle', 'green'], ['Pending Approval', '1', 'clock', 'orange'], ['Suspended', '1', 'slash', 'red']], search: 'Search properties...', filters: ['status'] },
};

export default function AdminDirectoryPage({ type, data }) {
  const config = configs[type]; const [search, setSearch] = useState(''); const [filters, setFilters] = useState({}); const [selected, setSelected] = useState(null); const [addOpen, setAddOpen] = useState(false); const [feedback, setFeedback] = useState(null);
  const rows = data.filter((row) => {
    const text = Object.values(row).join(' ').toLowerCase();
    return text.includes(search.toLowerCase()) && Object.entries(filters).every(([key, value]) => !value || value === 'all' || String(row[key]).toLowerCase() === value);
  });
  const columns = type === 'users' ? [{ key: 'name', label: 'User', render: (value, row) => <div><strong>{value}</strong><div className="table-subtext">{row.email}</div></div> }, { key: 'role', label: 'Role' }, { key: 'phone', label: 'Phone' }, { key: 'status', label: 'Status', render: (value) => <StatusBadge status={value} /> }, { key: 'joined', label: 'Joined' }, { key: 'actions', label: '', align: 'right', render: (_, row) => <Button size="xs" variant="ghost" onClick={() => setSelected(row)}>View</Button> }]
    : type === 'owners' ? [{ key: 'name', label: 'Owner', render: (value, row) => <div><strong>{value}</strong><div className="table-subtext">{row.email}</div></div> }, { key: 'properties', label: 'Properties' }, { key: 'units', label: 'Units' }, { key: 'tenants', label: 'Tenants' }, { key: 'status', label: 'Status', render: (value) => <StatusBadge status={value} /> }, { key: 'joined', label: 'Joined' }, { key: 'actions', label: '', align: 'right', render: (_, row) => <Button size="xs" variant="ghost" onClick={() => setSelected(row)}>View</Button> }]
    : type === 'tenants' ? [{ key: 'name', label: 'Tenant', render: (value) => <strong>{value}</strong> }, { key: 'property', label: 'Property' }, { key: 'flat', label: 'Flat' }, { key: 'owner', label: 'Owner' }, { key: 'status', label: 'Status', render: (value) => <StatusBadge status={value} /> }, { key: 'joined', label: 'Joined' }, { key: 'actions', label: '', align: 'right', render: (_, row) => <Button size="xs" variant="ghost" onClick={() => setSelected(row)}>View</Button> }]
    : [{ key: 'name', label: 'Property', render: (value, row) => <div><strong>{value}</strong><div className="table-subtext">{row.address}</div></div> }, { key: 'owner', label: 'Owner' }, { key: 'units', label: 'Units' }, { key: 'occupied', label: 'Occupied' }, { key: 'vacant', label: 'Vacant' }, { key: 'status', label: 'Status', render: (value) => <StatusBadge status={value} /> }, { key: 'created', label: 'Created' }, { key: 'actions', label: '', align: 'right', render: (_, row) => <Button size="xs" variant="ghost" onClick={() => setSelected(row)}>View</Button> }];
  const submit = (event) => { event.preventDefault(); setAddOpen(false); setFeedback(`${config.title.slice(0, -1)} added in this frontend preview.`); };
  const filterOptions = { role: [{ value: 'all', label: 'All roles' }, { value: 'owner', label: 'Owner' }, { value: 'tenant', label: 'Tenant' }, { value: 'administrator', label: 'Administrator' }], status: [{ value: 'all', label: 'All statuses' }, { value: 'active', label: 'Active' }, { value: 'pending', label: 'Pending' }, { value: 'suspended', label: 'Suspended' }, { value: 'inactive', label: 'Inactive' }], property: [{ value: 'all', label: 'All properties' }, { value: 'abc residence', label: 'ABC Residence' }, { value: 'green view apartments', label: 'Green View Apartments' }], owner: [{ value: 'all', label: 'All owners' }, { value: 'rahman ahmed', label: 'Rahman Ahmed' }, { value: 'farhan hossain', label: 'Farhan Hossain' }] };
  return <div className="admin-page"><PageHeader title={config.title} description={config.description} actions={<Button variant="primary" icon={<Icon name="plus" size={16} />} onClick={() => setAddOpen(true)}>Add {type === 'users' ? 'User' : type.slice(0, -1)}</Button>} /><div className="admin-summary-grid">{config.summary.map(([title, value, icon, color]) => <StatCard key={title} title={title} value={value} iconName={icon} iconColor={color} />)}</div><div className="admin-filter-bar"><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder={config.search} />{config.filters.map((key) => <Select key={key} value={filters[key] || 'all'} onChange={(event) => setFilters({ ...filters, [key]: event.target.value })} options={filterOptions[key]} />)}</div><Card><Table title={`${config.title} Directory`} columns={columns} data={rows} /></Card><Modal isOpen={Boolean(selected)} onClose={() => setSelected(null)} title={`${config.title.slice(0, -1)} Details`} size="md" footer={<AdminModalActions onCancel={() => setSelected(null)} submitLabel="Close" />}><form onSubmit={(event) => { event.preventDefault(); setSelected(null); }}>{selected && <div className="admin-detail-list">{Object.entries(selected).filter(([key]) => key !== 'id').map(([key, value]) => <div key={key}><span>{key.replace(/([A-Z])/g, ' $1')}</span><strong>{String(value)}</strong></div>)}</div>}</form></Modal><Modal isOpen={addOpen} onClose={() => setAddOpen(false)} title={`Add ${type === 'users' ? 'User' : type.slice(0, -1)}`} size="md" footer={<AdminModalActions onCancel={() => setAddOpen(false)} onSubmit={submit} submitLabel="Create" />}><form onSubmit={submit}><AdminFieldGrid><FormGroup label="Full Name" required><Input placeholder="Enter full name" required /></FormGroup><FormGroup label="Email" required><Input type="email" placeholder="user@example.com" required /></FormGroup></AdminFieldGrid><AdminFieldGrid><FormGroup label="Phone"><Input placeholder="+880 1XXX-XXXXXX" /></FormGroup><FormGroup label="Status"><Select options={filterOptions.status} /></FormGroup></AdminFieldGrid><FormGroup label="Role"><Select options={filterOptions.role} /></FormGroup></form></Modal><AdminFeedback message={feedback} onClose={() => setFeedback(null)} /></div>;
}
