import React, { useState } from 'react';
import PageHeader from '../../components/layout/PageHeader';
import Card from '../../components/common/Card';
import StatCard from '../../components/common/StatCard';
import Button from '../../components/common/Button';
import Icon from '../../components/common/Icon';
import Select from '../../components/common/Select';
import { adminReportData } from '../../data/adminPortalData';
import { AdminFeedback } from './components/AdminPageTools';

export default function AdminReports() {
	const [feedback, setFeedback] = useState(null); const { summary, userGrowth, activity } = adminReportData;
	return <div className="admin-page"><PageHeader title="Reports" description="Analyze platform-wide growth, activity, and support performance." actions={<><Button variant="secondary" icon={<Icon name="download" size={16} />} onClick={() => setFeedback('Report export prepared for download.')}>Export Report</Button><Button variant="primary" icon={<Icon name="file-text" size={16} />} onClick={() => setFeedback('Platform report generated.')}>Generate Report</Button></>} /><div className="admin-report-filters"><Select options={[{ value: 'month', label: 'Last 30 days' }, { value: 'quarter', label: 'Last quarter' }]} /><Select options={[{ value: 'platform', label: 'Platform Overview' }, { value: 'growth', label: 'Growth Report' }]} /><Select options={[{ value: 'all', label: 'All roles' }, { value: 'owner', label: 'Owners' }, { value: 'tenant', label: 'Tenants' }]} /><Select options={[{ value: 'all', label: 'All statuses' }, { value: 'active', label: 'Active' }]} /></div><div className="admin-summary-grid admin-summary-grid--five"><StatCard title="Total Users" value={summary.totalUsers} iconName="users" iconColor="blue" /><StatCard title="New Users" value={summary.newUsers} iconName="user-plus" iconColor="green" /><StatCard title="Active Properties" value={summary.activeProperties} iconName="building" iconColor="purple" /><StatCard title="Support Tickets" value={summary.supportTickets} iconName="headphones" iconColor="orange" /><StatCard title="Payment Transactions" value={summary.paymentTransactions} iconName="credit-card" iconColor="blue" /></div><div className="admin-reports-grid"><Card title="User Growth"><div className="admin-growth-chart">{userGrowth.map((item) => <div className="admin-growth-column" key={item.label}><span style={{ height: `${(item.value / 1300) * 100}%` }} title={`${item.value} users`} /><small>{item.label}</small></div>)}</div></Card><Card title="Owner vs Tenant Distribution"><div className="admin-distribution"><div className="admin-donut"><strong>1,188</strong><span>Accounts</span></div><div className="admin-distribution-legend"><span><i className="legend-owner" />Owners <b>86</b></span><span><i className="legend-tenant" />Tenants <b>1,102</b></span></div></div></Card><Card title="Platform Activity"><div className="admin-mini-bars">{activity.map((item) => <div key={item.label}><span style={{ height: `${(item.logins / 1300) * 100}%` }} /><i style={{ height: `${(item.tickets / 25) * 100}%` }} /><small>{item.label}</small></div>)}</div></Card><Card title="Support Ticket Trends"><div className="report-metric-list"><div><span>Open</span><strong className="text-danger">12</strong></div><div><span>In Progress</span><strong>18</strong></div><div><span>Resolved this month</span><strong className="text-success">64</strong></div><div><span>Average response</span><strong>2h 18m</strong></div></div></Card></div><AdminFeedback message={feedback} onClose={() => setFeedback(null)} /></div>;
}
