import React, { useState } from 'react';
import PageHeader from '../../components/layout/PageHeader';
import Button from '../../components/common/Button';
import Input from '../../components/common/Input';
import Icon from '../../components/common/Icon';
import Avatar from '../../components/common/Avatar';
import { adminConversations } from '../../data/adminPortalData';
import { AdminFeedback } from './components/AdminPageTools';

export default function AdminMessages() {
	const [selectedId, setSelectedId] = useState('rahim'); const [message, setMessage] = useState(''); const [feedback, setFeedback] = useState(null); const selected = adminConversations.find((item) => item.id === selectedId) || adminConversations[0];
	const send = (event) => { event.preventDefault(); if (!message.trim()) return; setMessage(''); setFeedback('Message queued in this frontend preview.'); };
	return <div className="admin-page"><PageHeader title="Messages" description="Review platform conversations and support communication." /><div className="messages-chat-layout"><aside className="messages-sidebar"><div className="messages-sidebar__search"><strong>Conversations</strong></div><div className="messages-threads-list">{adminConversations.map((conversation) => <button type="button" key={conversation.id} className={`messages-thread-item ${selected.id === conversation.id ? 'active' : ''}`} onClick={() => setSelectedId(conversation.id)}><Avatar name={conversation.name} size="sm" color={conversation.avatarColor} /><div className="messages-thread-content"><div className="messages-thread-name">{conversation.name}</div><div className="messages-thread-role">{conversation.role}</div><div className="messages-thread-preview">{conversation.messages[conversation.messages.length - 1].text}</div></div></button>)}</div></aside><section className="messages-chat-pane"><header className="messages-chat-header"><div className="messages-chat-header__identity"><Avatar name={selected.name} size="sm" color={selected.avatarColor} /><div><strong>{selected.name}</strong><div className="table-subtext">{selected.role}</div></div></div><Button size="sm" variant="secondary" icon={<Icon name="user" size={15} />}>View Profile</Button></header><div className="messages-chat-body">{selected.messages.map((item, index) => <div key={`${item.time}-${index}`} className={`chat-bubble chat-bubble--${item.isMe ? 'me' : 'them'}`}>{item.text}<span className="chat-bubble-time">{item.time}</span></div>)}</div><form className="messages-chat-footer" onSubmit={send}><Input value={message} onChange={(event) => setMessage(event.target.value)} placeholder="Write a message..." /><Button type="submit" variant="primary" icon={<Icon name="send" size={16} />} aria-label="Send message">Send</Button></form></section></div><AdminFeedback message={feedback} onClose={() => setFeedback(null)} /></div>;
}
