import React, { useState } from 'react';
import PageHeader from '../../components/layout/PageHeader';
import Card from '../../components/common/Card';
import StatCard from '../../components/common/StatCard';
import Button from '../../components/common/Button';
import Input from '../../components/common/Input';
import Select from '../../components/common/Select';
import FormGroup from '../../components/common/FormGroup';
import Modal from '../../components/common/Modal';
import StatusBadge from '../../components/common/StatusBadge';
import Badge from '../../components/common/Badge';
import Table from '../../components/tables/Table';
import { adminSupportTickets } from '../../data/adminPortalData';
import { AdminFeedback, AdminFieldGrid, AdminModalActions } from './components/AdminPageTools';

export default function AdminSupport() {
	const [search, setSearch] = useState(''); const [status, setStatus] = useState('all'); const [priority, setPriority] = useState('all'); const [selected, setSelected] = useState(null); const [feedback, setFeedback] = useState(null);
	const rows = adminSupportTickets.filter((ticket) => (status === 'all' || ticket.status.toLowerCase().replace(' ', '-') === status) && (priority === 'all' || ticket.priority.toLowerCase() === priority) && `${ticket.id} ${ticket.subject} ${ticket.submittedBy}`.toLowerCase().includes(search.toLowerCase()));
	const columns = [{ key: 'id', label: 'Ticket ID', render: (value) => <strong className="admin-id">{value}</strong> }, { key: 'subject', label: 'Subject' }, { key: 'submittedBy', label: 'Submitted By' }, { key: 'role', label: 'Role' }, { key: 'priority', label: 'Priority', render: (value) => <Badge variant={value === 'High' ? 'danger' : value === 'Medium' ? 'warning' : 'neutral'}>{value}</Badge> }, { key: 'status', label: 'Status', render: (value) => <StatusBadge status={value} /> }, { key: 'created', label: 'Created' }, { key: 'assignedTo', label: 'Assigned To' }, { key: 'actions', label: '', align: 'right', render: (_, row) => <Button size="xs" variant="ghost" onClick={() => setSelected(row)}>View</Button> }];
	return <div className="admin-page"><PageHeader title="Support Tickets" description="Resolve platform issues and coordinate support activity." /><div className="admin-summary-grid admin-summary-grid--four"><StatCard title="Open" value="12" iconName="alert-circle" iconColor="red" /><StatCard title="In Progress" value="18" iconName="clock" iconColor="orange" /><StatCard title="Pending" value="11" iconName="pause-circle" iconColor="purple" /><StatCard title="Resolved" value="6" iconName="check-circle" iconColor="green" /></div><div className="admin-filter-bar"><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search tickets, subjects, or users..." /><Select value={status} onChange={(event) => setStatus(event.target.value)} options={[{ value: 'all', label: 'All statuses' }, { value: 'open', label: 'Open' }, { value: 'in-progress', label: 'In Progress' }, { value: 'pending', label: 'Pending' }, { value: 'resolved', label: 'Resolved' }]} /><Select value={priority} onChange={(event) => setPriority(event.target.value)} options={[{ value: 'all', label: 'All priorities' }, { value: 'high', label: 'High' }, { value: 'medium', label: 'Medium' }, { value: 'low', label: 'Low' }]} /></div><Card><Table title="Ticket Queue" columns={columns} data={rows} /></Card><Modal isOpen={Boolean(selected)} onClose={() => setSelected(null)} title={`${selected?.id || ''} Support Ticket`} size="lg" footer={<AdminModalActions onCancel={() => setSelected(null)} submitLabel="Close" />}><form onSubmit={(event) => { event.preventDefault(); setSelected(null); setFeedback('Ticket updated in this frontend preview.'); }}>{selected && <><div className="ticket-detail-head"><div><span>{selected.subject}</span><strong>{selected.submittedBy} · {selected.role}</strong></div><StatusBadge status={selected.status} /></div><p className="ticket-description">{selected.description}</p><AdminFieldGrid><FormGroup label="Priority"><Select defaultValue={selected.priority.toLowerCase()} options={[{ value: 'high', label: 'High' }, { value: 'medium', label: 'Medium' }, { value: 'low', label: 'Low' }]} /></FormGroup><FormGroup label="Assigned To"><Select options={[{ value: 'support', label: 'Support Team' }, { value: 'engineering', label: 'Engineering' }, { value: 'unassigned', label: 'Unassigned' }]} /></FormGroup></AdminFieldGrid><div className="ticket-timeline">{selected.timeline.map((item) => <div key={item}><i />{item}</div>)}</div></>}</form></Modal><AdminFeedback message={feedback} onClose={() => setFeedback(null)} /></div>;
}
